apiVersion: v1
kind: Service
metadata:
  name: nodeport-service
spec:
  selector:
    app: node-app
  ports:
    - protocol: TCP
      port: 31001
      nodePort:  31001
      targetPort: nodejs-port
  type: NodePort